name: flutter_test_moteis_go
description: "This project showcases simple architecture with Flutter, incorporating key principles like SOLID, Dependency Injection, and more. Let's dive into the details!"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sticky_headers: ^0.3.0+2
  smooth_page_indicator: ^1.2.0+3
  dio: ^5.8.0+1
  resultfy: ^1.0.0
  injectfy: ^1.0.1
  intl: ^0.20.2
  skeletonizer: ^1.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
